### ISSUE TITLE
Ctrl-c exception

### ISSUE THREAD

**Issue by muammar** [joeyespo/py-getch#4]
Thanks for writing this module. I have recently used it, but as far as I can say it is not possible to make `py-getch` to listen to `KeyboardInterrupt`. The thing is that I want to listen to some keys, but I also want to give the freedom of using `Ctrl-c` to kill the application. Is it possible to do so with `py-getch`?. 

Cheers.

**Comment by MattTuttle** [comment]
You can check if the value returned equals 3 (ascii break).

**Comment by joeyespo** [comment]
Thanks for chiming in, @MattTuttle!

Yeah, the implementation should work cross-platform. With `from msvcrt import getch`, running `getch()` also returns 3 (well, `'\x03'`) instead of raising `KeyboardInterrupt`. Checking for that value should give you what you need on all platforms. Specifically:

``` py
if getch() == '\x03':
    raise KeyboardInterrupt()
```

Thanks for the issue, @muammar!

**Comment by muammar** [comment]
@MattTuttle and @joeyespo, yes that worked. I had no idea that `'\x03'` was registered as `Ctrl-C`. Sorry for the ignorance, and thanks for replying :). Cheers.

**Comment by joeyespo** [comment]
@muammar No worries! I agree, this breaks the principle of least surprise. If I was designing `getch` from scratch, it would follow normal "raise KeyboardInterrupt " logic like `raw_input()` and most other blocking input functions do. But In this case, compatibility is more important, so naturally, you have to go digging around to figure out what to do. Glad py-getch is helping you!
